[tool.poetry]
name = "main-project"
version = "0.1.0"
description = ""
authors = ["Альберт Хабиров <alb.xab@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
